### ISSUE TITLE
Auto reload home page

### ISSUE THREAD

**Issue by fhoshino** [sekai-soft/pill-city#103]
Push out the comment in ajax

**Comment by KTachibanaM** [comment]
Frontend homepage poling logic
1) maintain a polling head ID (because top of posts list may be the current user's newly created post)
2) recurrently poll latest posts, if nothing, no-op
3) if there are latest posts but they are the exact same with all posts beyond polling head ID (meaning all new posts are the posts the current user himself posts), update polling head ID but do not show new post indicator and no-op on posts list
4) otherwise, also update polling head ID, show new post indicator and prefix new posts to posts list
